import { lazy } from 'react';

const toolComponents = {
    // Text Tools
    'word-counter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.WordCounter }))),
    'character-counter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.CharacterCounter }))),
    'sentence-counter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.SentenceCounter }))),
    'paragraph-counter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.ParagraphCounter }))),
    'reading-time': lazy(() => import('./tools/TextTools').then(m => ({ default: m.ReadingTimeCalculator }))),
    'case-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.CaseConverter }))),
    'uppercase-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.UppercaseConverter }))),
    'lowercase-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.LowercaseConverter }))),
    'title-case-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.TitleCaseConverter }))),
    'sentence-case-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.SentenceCaseConverter }))),
    'reverse-text': lazy(() => import('./tools/TextTools').then(m => ({ default: m.ReverseText }))),
    'remove-extra-spaces': lazy(() => import('./tools/TextTools').then(m => ({ default: m.RemoveSpaces }))),
    'remove-duplicate-lines': lazy(() => import('./tools/TextTools').then(m => ({ default: m.RemoveDuplicates }))),
    'remove-empty-lines': lazy(() => import('./tools/TextTools').then(m => ({ default: m.RemoveEmptyLines }))),
    'sort-lines': lazy(() => import('./tools/TextTools').then(m => ({ default: m.SortLines }))),
    'shuffle-text': lazy(() => import('./tools/TextTools').then(m => ({ default: m.ShuffleText }))),
    'random-text-generator': lazy(() => import('./tools/TextTools').then(m => ({ default: m.RandomTextGenerator }))),
    'lorem-ipsum-generator': lazy(() => import('./tools/TextTools').then(m => ({ default: m.LoremIpsumGenerator }))),
    'text-repeater': lazy(() => import('./tools/TextTools').then(m => ({ default: m.TextRepeater }))),
    'find-and-replace': lazy(() => import('./tools/TextTools').then(m => ({ default: m.FindAndReplace }))),
    'slug-generator': lazy(() => import('./tools/TextTools').then(m => ({ default: m.SlugGenerator }))),
    'url-encoder': lazy(() => import('./tools/TextTools').then(m => ({ default: m.URLEncoder }))),
    'url-decoder': lazy(() => import('./tools/TextTools').then(m => ({ default: m.URLDecoder }))),
    'html-encoder': lazy(() => import('./tools/TextTools').then(m => ({ default: m.HTMLEncoder }))),
    'html-decoder': lazy(() => import('./tools/TextTools').then(m => ({ default: m.HTMLDecoder }))),
    'unicode-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.UnicodeConverter }))),
    'ascii-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.ASCIIConverter }))),
    'binary-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.BinaryConverter }))),
    'hex-converter': lazy(() => import('./tools/TextTools').then(m => ({ default: m.HexConverter }))),
    'morse-code-generator': lazy(() => import('./tools/TextTools').then(m => ({ default: m.MorseEncoder }))),
    'morse-code-decoder': lazy(() => import('./tools/TextTools').then(m => ({ default: m.MorseDecoder }))),

    // Developer Tools
    'json-formatter': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JsonFormatter }))),
    'json-validator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JsonValidator }))),
    'json-minifier': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JsonMinifier }))),
    'json-beautifier': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JsonBeautifier }))),
    'xml-formatter': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.XmlFormatter }))),
    'xml-validator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.XmlValidator }))),
    'html-formatter': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.HtmlFormatter }))),
    'css-beautifier': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.CssBeautifier }))),
    'css-minifier': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.CssMinifier }))),
    'js-beautifier': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JSBeautifier }))),
    'js-minifier': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JSMinifier }))),
    'sql-formatter': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.SqlFormatter }))),
    'markdown-preview': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.MarkdownPreview }))),
    'markdown-to-html': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.MarkdownToHtml }))),
    'html-to-markdown': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.HtmlToMarkdown }))),
    'html-escape': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.HtmlEscape }))),
    'regex-tester': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.RegexTester }))),
    'regex-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.RegexGenerator }))),
    'base64-encode': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.Base64Encode }))),
    'base64-decode': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.Base64Decode }))),
    'jwt-decoder': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JwtDecoder }))),
    'jwt-parser': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.JwtParser }))),
    'uuid-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.UuidGenerator }))),
    'hash-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.HashGenerator }))),
    'sha256-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.Sha256Generator }))),
    'md5-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.Md5Generator }))),
    'hmac-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.HmacGenerator }))),
    'unix-timestamp-converter': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.UnixTimestamp }))),
    'timestamp-to-date': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.TimestampToDate }))),
    'cron-expression-generator': lazy(() => import('./tools/DeveloperTools').then(m => ({ default: m.CronGenerator }))),

    // Calculator Tools
    'percentage-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.PercentageCalculator }))),
    'age-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.AgeCalculator }))),
    'date-difference-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.DateDifferenceCalculator }))),
    'time-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.TimeCalculator }))),
    'hour-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.HourCalculator }))),
    'gpa-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.GpaCalculator }))),
    'cgpa-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.CgpaCalculator }))),
    'grade-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.GradeCalculator }))),
    'marks-percentage-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.MarksPercentageCalculator }))),
    'average-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.AverageCalculator }))),
    'discount-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.DiscountCalculator }))),
    'gst-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.GstCalculator }))),
    'vat-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.VatCalculator }))),
    'profit-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.ProfitCalculator }))),
    'loss-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.LossCalculator }))),
    'emi-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.EmiCalculator }))),
    'loan-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.LoanCalculator }))),
    'sip-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.SipCalculator }))),
    'fd-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.FdCalculator }))),
    'compound-interest-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.CompoundInterestCalculator }))),
    'simple-interest-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.SimpleInterestCalculator }))),
    'tip-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.TipCalculator }))),
    'split-bill-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.SplitBillCalculator }))),
    'unit-price-calculator': lazy(() => import('./tools/CalculatorTools').then(m => ({ default: m.UnitPriceCalculator }))),

    // Math Tools
    'scientific-calculator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.ScientificCalculator }))),
    'fraction-calculator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.FractionCalculator }))),
    'percentage-increase': lazy(() => import('./tools/MathTools').then(m => ({ default: m.PctIncrease }))),
    'percentage-decrease': lazy(() => import('./tools/MathTools').then(m => ({ default: m.PctDecrease }))),
    'ratio-calculator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.RatioCalculator }))),
    'lcm-calculator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.LcmCalculator }))),
    'hcf-calculator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.HcfCalculator }))),
    'prime-number-checker': lazy(() => import('./tools/MathTools').then(m => ({ default: m.PrimeNumberChecker }))),
    'prime-number-generator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.PrimeNumberGenerator }))),
    'even-odd-checker': lazy(() => import('./tools/MathTools').then(m => ({ default: m.EvenOddChecker }))),
    'random-number-generator': lazy(() => import('./tools/MathTools').then(m => ({ default: m.RandomNumberGenerator }))),
    'dice-roller': lazy(() => import('./tools/MathTools').then(m => ({ default: m.DiceRoller }))),
    'coin-flip': lazy(() => import('./tools/MathTools').then(m => ({ default: m.CoinFlip }))),
    'number-to-words': lazy(() => import('./tools/MathTools').then(m => ({ default: m.NumberToWords }))),
    'roman-number-converter': lazy(() => import('./tools/MathTools').then(m => ({ default: m.RomanNumberConverter }))),

    // Color Tools
    'color-picker': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.ColorPicker }))),
    'hex-to-rgb': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.HexToRgb }))),
    'rgb-to-hex': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.RgbToHex }))),
    'hex-to-hsl': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.HexToHsl }))),
    'hsl-to-hex': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.HslToHex }))),
    'rgb-to-cmyk': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.RgbToCmyk }))),
    'color-palette-generator': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.ColorPaletteGenerator }))),
    'gradient-generator': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.GradientGenerator }))),
    'css-gradient-generator': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.CssGradientGenerator }))),
    'contrast-checker': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.ContrastChecker }))),
    'random-color-generator': lazy(() => import('./tools/ColorTools').then(m => ({ default: m.RandomColorGenerator }))),

    // Image Tools
    'image-compressor': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.ImageCompressor }))),
    'image-resizer': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.ImageResizer }))),
    'crop-image': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.CropImage }))),
    'rotate-image': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.RotateImage }))),
    'flip-image': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.FlipImage }))),
    'png-to-jpg': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.PngToJpg }))),
    'jpg-to-png': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.JpgToPng }))),
    'webp-to-jpg': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.WebpToJpg }))),
    'jpg-to-webp': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.JpgToWebp }))),
    'image-to-base64': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.ImageToBase64 }))),
    'base64-to-image': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.Base64ToImage }))),
    'blur-image': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.BlurImage }))),
    'brightness-adjuster': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.BrightnessAdjuster }))),
    'contrast-adjuster': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.ContrastAdjuster }))),
    'grayscale-converter': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.GrayscaleConverter }))),
    'bw-converter': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.BwConverter }))),
    'rounded-corners-generator': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.RoundedCornersGenerator }))),
    'watermark-image': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.WatermarkImage }))),
    'image-metadata-viewer': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.ImageMetadataViewer }))),
    'image-dimension-checker': lazy(() => import('./tools/ImageTools').then(m => ({ default: m.ImageDimensionChecker }))),

    // PDF Tools
    'merge-pdf': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.MergePdf }))),
    'split-pdf': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.SplitPdf }))),
    'rotate-pdf': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.RotatePdf }))),
    'delete-pdf-pages': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.DeletePdfPages }))),
    'extract-pdf-pages': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.ExtractPdfPages }))),
    'compress-pdf': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.CompressPdf }))),
    'add-page-numbers': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.AddPageNumbers }))),
    'pdf-page-counter': lazy(() => import('./tools/PdfTools').then(m => ({ default: m.PdfPageCounter }))),

    // File Conversion Tools
    'pdf-to-docx': lazy(() => import('./tools/FileConversionTools').then(m => ({ default: m.PdfToDocx }))),
    'pdf-to-xlsx': lazy(() => import('./tools/FileConversionTools').then(m => ({ default: m.PdfToXlsx }))),
    'docx-to-pdf': lazy(() => import('./tools/FileConversionTools').then(m => ({ default: m.DocxToPdf }))),
    'xlsx-to-pdf': lazy(() => import('./tools/FileConversionTools').then(m => ({ default: m.XlsxToPdf }))),

    // QR & Barcode
    'qr-code-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.QrCodeGenerator }))),
    'qr-code-scanner': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.QrCodeScanner }))),
    'wifi-qr-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.WifiQrGenerator }))),
    'whatsapp-qr': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.WhatsAppQr }))),
    'email-qr': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.EmailQr }))),
    'sms-qr': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.SmsQr }))),
    'vcard-qr': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.VCardQr }))),
    'barcode-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.BarcodeGenerator }))),

    // Password & Security
    'password-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.PasswordGenerator }))),
    'password-strength-checker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.PasswordStrengthChecker }))),
    'pin-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.PinGenerator }))),
    'random-string-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RandomStringGenerator }))),
    'random-username-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RandomUsernameGenerator }))),
    'random-otp-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RandomOtpGenerator }))),

    // Date & Time
    'birthday-countdown': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.BirthdayCountdown }))),
    'leap-year-checker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.LeapYearChecker }))),
    'timezone-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.TimeZoneConverter }))),
    'countdown-timer': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.CountdownTimer }))),
    'stopwatch': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.Stopwatch }))),
    'digital-clock': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.DigitalClock }))),
    'calendar-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.CalendarGenerator }))),
    'week-number-calculator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.WeekNumberCalculator }))),

    // SEO
    'meta-tag-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.MetaTagGenerator }))),
    'open-graph-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.OpenGraphGenerator }))),
    'robots-txt-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RobotsTxtGenerator }))),
    'sitemap-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.SitemapGenerator }))),
    'keyword-density-checker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.KeywordDensityChecker }))),
    'url-slug-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.UrlSlugGeneratorText }))),

    // Social Media
    'youtube-title-checker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.YoutubeTitleChecker }))),
    'youtube-tag-formatter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.YoutubeTagFormatter }))),
    'hashtag-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.HashtagGenerator }))),
    'instagram-caption-formatter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.InstagramCaptionFormatter }))),
    'tweet-character-counter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.TweetCharacterCounter }))),

    // File Tools
    'file-size-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.FileSizeConverter }))),
    'zip-size-estimator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.ZipSizeEstimator }))),
    'file-extension-checker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.FileExtensionChecker }))),
    'mime-type-checker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.MimeTypeChecker }))),

    // Unit Converters
    'length-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.LengthConverter }))),
    'weight-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.WeightConverter }))),
    'area-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.AreaConverter }))),
    'volume-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.VolumeConverter }))),
    'temperature-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.TemperatureConverter }))),
    'speed-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.SpeedConverter }))),
    'time-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.TimeUnitConverter }))),
    'currency-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.CurrencyConverter }))),
    'storage-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.StorageConverter }))),
    'energy-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.EnergyConverter }))),
    'pressure-converter': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.PressureConverter }))),

    // Fun Tools
    'random-name-picker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RandomNamePicker }))),
    'random-team-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RandomTeamGenerator }))),
    'random-quote-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.RandomQuoteGenerator }))),
    'lucky-number-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.LuckyNumberGenerator }))),
    'spin-wheel': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.SpinWheel }))),
    'decision-maker': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.DecisionMaker }))),
    'yes-no-generator': lazy(() => import('./tools/MiscTools').then(m => ({ default: m.YesNoGenerator }))),
};

export default toolComponents;