import {
    Type, Code2, Calculator, Binary, Palette, Image, FileText,
    QrCode, Shield, Clock, Search, MessageSquare, FolderOpen,
    ArrowLeftRight, Gamepad2, Hash, Braces, FileCode, FileImage,
    Lock, Calendar, Globe, Smartphone, HardDrive, Shuffle, Dice5,
    ArrowRightLeft
} from 'lucide-react';

export const categories = [
    {
        id: 'text',
        name: 'Text Tools',
        icon: Type,
        color: 'from-blue-500 to-blue-600',
        description: 'Text manipulation & analysis',
        tools: [
            { id: 'word-counter', name: 'Word Counter' },
            { id: 'character-counter', name: 'Character Counter' },
            { id: 'sentence-counter', name: 'Sentence Counter' },
            { id: 'paragraph-counter', name: 'Paragraph Counter' },
            { id: 'reading-time', name: 'Reading Time Calculator' },
            { id: 'case-converter', name: 'Case Converter' },
            { id: 'uppercase-converter', name: 'Uppercase Converter' },
            { id: 'lowercase-converter', name: 'Lowercase Converter' },
            { id: 'title-case-converter', name: 'Title Case Converter' },
            { id: 'sentence-case-converter', name: 'Sentence Case Converter' },
            { id: 'reverse-text', name: 'Reverse Text' },
            { id: 'remove-extra-spaces', name: 'Remove Extra Spaces' },
            { id: 'remove-duplicate-lines', name: 'Remove Duplicate Lines' },
            { id: 'remove-empty-lines', name: 'Remove Empty Lines' },
            { id: 'sort-lines', name: 'Sort Lines' },
            { id: 'shuffle-text', name: 'Shuffle Text' },
            { id: 'random-text-generator', name: 'Random Text Generator' },
            { id: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator' },
            { id: 'text-repeater', name: 'Text Repeater' },
            { id: 'find-and-replace', name: 'Find and Replace' },
            { id: 'slug-generator', name: 'Slug Generator' },
            { id: 'url-encoder', name: 'URL Encoder' },
            { id: 'url-decoder', name: 'URL Decoder' },
            { id: 'html-encoder', name: 'HTML Encoder' },
            { id: 'html-decoder', name: 'HTML Decoder' },
            { id: 'unicode-converter', name: 'Unicode Converter' },
            { id: 'ascii-converter', name: 'ASCII Converter' },
            { id: 'binary-converter', name: 'Binary Converter' },
            { id: 'hex-converter', name: 'Hex Converter' },
            { id: 'morse-code-generator', name: 'Morse Code Generator' },
            { id: 'morse-code-decoder', name: 'Morse Code Decoder' },
        ]
    },
    {
        id: 'developer',
        name: 'Developer Tools',
        icon: Code2,
        color: 'from-emerald-500 to-emerald-600',
        description: 'Code formatting & debugging',
        tools: [
            { id: 'json-formatter', name: 'JSON Formatter' },
            { id: 'json-validator', name: 'JSON Validator' },
            { id: 'json-minifier', name: 'JSON Minifier' },
            { id: 'json-beautifier', name: 'JSON Beautifier' },
            { id: 'xml-formatter', name: 'XML Formatter' },
            { id: 'xml-validator', name: 'XML Validator' },
            { id: 'html-formatter', name: 'HTML Formatter' },
            { id: 'css-beautifier', name: 'CSS Beautifier' },
            { id: 'css-minifier', name: 'CSS Minifier' },
            { id: 'js-beautifier', name: 'JavaScript Beautifier' },
            { id: 'js-minifier', name: 'JavaScript Minifier' },
            { id: 'sql-formatter', name: 'SQL Formatter' },
            { id: 'markdown-preview', name: 'Markdown Preview' },
            { id: 'markdown-to-html', name: 'Markdown to HTML' },
            { id: 'html-to-markdown', name: 'HTML to Markdown' },
            { id: 'html-escape', name: 'HTML Escape' },
            { id: 'regex-tester', name: 'Regex Tester' },
            { id: 'regex-generator', name: 'Regex Generator' },
            { id: 'base64-encode', name: 'Base64 Encode' },
            { id: 'base64-decode', name: 'Base64 Decode' },
            { id: 'jwt-decoder', name: 'JWT Decoder' },
            { id: 'jwt-parser', name: 'JWT Parser' },
            { id: 'uuid-generator', name: 'UUID Generator' },
            { id: 'hash-generator', name: 'Hash Generator' },
            { id: 'sha256-generator', name: 'SHA256 Generator' },
            { id: 'md5-generator', name: 'MD5 Generator' },
            { id: 'hmac-generator', name: 'HMAC Generator' },
            { id: 'unix-timestamp-converter', name: 'Unix Timestamp Converter' },
            { id: 'timestamp-to-date', name: 'Timestamp to Date' },
            { id: 'cron-expression-generator', name: 'Cron Expression Generator' },
        ]
    },
    {
        id: 'calculator',
        name: 'Calculator Tools',
        icon: Calculator,
        color: 'from-orange-500 to-orange-600',
        description: 'Financial & general calculators',
        tools: [
            { id: 'percentage-calculator', name: 'Percentage Calculator' },
            { id: 'age-calculator', name: 'Age Calculator' },
            { id: 'date-difference-calculator', name: 'Date Difference Calculator' },
            { id: 'time-calculator', name: 'Time Calculator' },
            { id: 'hour-calculator', name: 'Hour Calculator' },
            { id: 'gpa-calculator', name: 'GPA Calculator' },
            { id: 'cgpa-calculator', name: 'CGPA Calculator' },
            { id: 'grade-calculator', name: 'Grade Calculator' },
            { id: 'marks-percentage-calculator', name: 'Marks Percentage Calculator' },
            { id: 'average-calculator', name: 'Average Calculator' },
            { id: 'discount-calculator', name: 'Discount Calculator' },
            { id: 'gst-calculator', name: 'GST Calculator' },
            { id: 'vat-calculator', name: 'VAT Calculator' },
            { id: 'profit-calculator', name: 'Profit Calculator' },
            { id: 'loss-calculator', name: 'Loss Calculator' },
            { id: 'emi-calculator', name: 'EMI Calculator' },
            { id: 'loan-calculator', name: 'Loan Calculator' },
            { id: 'sip-calculator', name: 'SIP Calculator' },
            { id: 'fd-calculator', name: 'FD Calculator' },
            { id: 'compound-interest-calculator', name: 'Compound Interest Calculator' },
            { id: 'simple-interest-calculator', name: 'Simple Interest Calculator' },
            { id: 'tip-calculator', name: 'Tip Calculator' },
            { id: 'split-bill-calculator', name: 'Split Bill Calculator' },
            { id: 'unit-price-calculator', name: 'Unit Price Calculator' },
        ]
    },
    {
        id: 'math',
        name: 'Math Tools',
        icon: Binary,
        color: 'from-purple-500 to-purple-600',
        description: 'Mathematical utilities',
        tools: [
            { id: 'scientific-calculator', name: 'Scientific Calculator' },
            { id: 'fraction-calculator', name: 'Fraction Calculator' },
            { id: 'percentage-increase', name: 'Percentage Increase Calculator' },
            { id: 'percentage-decrease', name: 'Percentage Decrease Calculator' },
            { id: 'ratio-calculator', name: 'Ratio Calculator' },
            { id: 'lcm-calculator', name: 'LCM Calculator' },
            { id: 'hcf-calculator', name: 'HCF Calculator' },
            { id: 'prime-number-checker', name: 'Prime Number Checker' },
            { id: 'prime-number-generator', name: 'Prime Number Generator' },
            { id: 'even-odd-checker', name: 'Even/Odd Checker' },
            { id: 'random-number-generator', name: 'Random Number Generator' },
            { id: 'dice-roller', name: 'Dice Roller' },
            { id: 'coin-flip', name: 'Coin Flip' },
            { id: 'number-to-words', name: 'Number to Words' },
            { id: 'roman-number-converter', name: 'Roman Number Converter' },
        ]
    },
    {
        id: 'color',
        name: 'Color Tools',
        icon: Palette,
        color: 'from-pink-500 to-pink-600',
        description: 'Color utilities & generators',
        tools: [
            { id: 'color-picker', name: 'Color Picker' },
            { id: 'hex-to-rgb', name: 'HEX to RGB' },
            { id: 'rgb-to-hex', name: 'RGB to HEX' },
            { id: 'hex-to-hsl', name: 'HEX to HSL' },
            { id: 'hsl-to-hex', name: 'HSL to HEX' },
            { id: 'rgb-to-cmyk', name: 'RGB to CMYK' },
            { id: 'color-palette-generator', name: 'Color Palette Generator' },
            { id: 'gradient-generator', name: 'Gradient Generator' },
            { id: 'css-gradient-generator', name: 'CSS Gradient Generator' },
            { id: 'contrast-checker', name: 'Contrast Checker' },
            { id: 'random-color-generator', name: 'Random Color Generator' },
        ]
    },
    {
        id: 'image',
        name: 'Image Tools',
        icon: Image,
        color: 'from-teal-500 to-teal-600',
        description: 'Image processing & conversion',
        tools: [
            { id: 'image-compressor', name: 'Image Compressor' },
            { id: 'image-resizer', name: 'Image Resizer' },
            { id: 'crop-image', name: 'Crop Image' },
            { id: 'rotate-image', name: 'Rotate Image' },
            { id: 'flip-image', name: 'Flip Image' },
            { id: 'png-to-jpg', name: 'PNG to JPG' },
            { id: 'jpg-to-png', name: 'JPG to PNG' },
            { id: 'webp-to-jpg', name: 'WEBP to JPG' },
            { id: 'jpg-to-webp', name: 'JPG to WEBP' },
            { id: 'image-to-base64', name: 'Image to Base64' },
            { id: 'base64-to-image', name: 'Base64 to Image' },
            { id: 'blur-image', name: 'Blur Image' },
            { id: 'brightness-adjuster', name: 'Brightness Adjuster' },
            { id: 'contrast-adjuster', name: 'Contrast Adjuster' },
            { id: 'grayscale-converter', name: 'Grayscale Converter' },
            { id: 'bw-converter', name: 'Black and White Converter' },
            { id: 'rounded-corners-generator', name: 'Rounded Corner Generator' },
            { id: 'watermark-image', name: 'Watermark Image' },
            { id: 'image-metadata-viewer', name: 'Image Metadata Viewer' },
            { id: 'image-dimension-checker', name: 'Image Dimension Checker' },
        ]
    },
    {
        id: 'pdf',
        name: 'PDF Tools',
        icon: FileText,
        color: 'from-red-500 to-red-600',
        description: 'PDF manipulation tools',
        tools: [
            { id: 'merge-pdf', name: 'Merge PDF' },
            { id: 'split-pdf', name: 'Split PDF' },
            { id: 'rotate-pdf', name: 'Rotate PDF' },
            { id: 'delete-pdf-pages', name: 'Delete PDF Pages' },
            { id: 'extract-pdf-pages', name: 'Extract PDF Pages' },
            { id: 'compress-pdf', name: 'Compress PDF' },
            { id: 'add-page-numbers', name: 'Add Page Numbers' },
            { id: 'pdf-page-counter', name: 'PDF Page Counter' },
        ]
    },
    {
        id: 'file-conversion',
        name: 'File Conversion',
        icon: ArrowRightLeft,
        color: 'from-amber-600 to-red-500',
        description: 'Convert between PDF, DOCX, and Excel formats',
        tools: [
            { id: 'pdf-to-docx', name: 'PDF to DOCX' },
            { id: 'pdf-to-xlsx', name: 'PDF to Excel' },
            { id: 'docx-to-pdf', name: 'DOCX to PDF' },
            { id: 'xlsx-to-pdf', name: 'Excel to PDF' },
        ]
    },
    {
        id: 'qrcode',
        name: 'QR & Barcode Tools',
        icon: QrCode,
        color: 'from-indigo-500 to-indigo-600',
        description: 'QR & barcode generators',
        tools: [
            { id: 'qr-code-generator', name: 'QR Code Generator' },
            { id: 'qr-code-scanner', name: 'QR Code Scanner' },
            { id: 'wifi-qr-generator', name: 'WiFi QR Generator' },
            { id: 'whatsapp-qr', name: 'WhatsApp QR' },
            { id: 'email-qr', name: 'Email QR' },
            { id: 'sms-qr', name: 'SMS QR' },
            { id: 'vcard-qr', name: 'vCard QR' },
            { id: 'barcode-generator', name: 'Barcode Generator' },
        ]
    },
    {
        id: 'password',
        name: 'Password & Security',
        icon: Shield,
        color: 'from-amber-500 to-amber-600',
        description: 'Password & security utilities',
        tools: [
            { id: 'password-generator', name: 'Password Generator' },
            { id: 'password-strength-checker', name: 'Password Strength Checker' },
            { id: 'pin-generator', name: 'PIN Generator' },
            { id: 'random-string-generator', name: 'Random String Generator' },
            { id: 'random-username-generator', name: 'Random Username Generator' },
            { id: 'random-otp-generator', name: 'Random OTP Generator' },
        ]
    },
    {
        id: 'datetime',
        name: 'Date & Time',
        icon: Clock,
        color: 'from-cyan-500 to-cyan-600',
        description: 'Date & time utilities',
        tools: [
            { id: 'age-calculator', name: 'Age Calculator' },
            { id: 'birthday-countdown', name: 'Birthday Countdown' },
            { id: 'leap-year-checker', name: 'Leap Year Checker' },
            { id: 'timezone-converter', name: 'Time Zone Converter' },
            { id: 'countdown-timer', name: 'Countdown Timer' },
            { id: 'stopwatch', name: 'Stopwatch' },
            { id: 'digital-clock', name: 'Digital Clock' },
            { id: 'calendar-generator', name: 'Calendar Generator' },
            { id: 'week-number-calculator', name: 'Week Number Calculator' },
        ]
    },
    {
        id: 'seo',
        name: 'SEO Tools',
        icon: Search,
        color: 'from-lime-500 to-lime-600',
        description: 'SEO & web optimization',
        tools: [
            { id: 'meta-tag-generator', name: 'Meta Tag Generator' },
            { id: 'open-graph-generator', name: 'Open Graph Generator' },
            { id: 'robots-txt-generator', name: 'Robots.txt Generator' },
            { id: 'sitemap-generator', name: 'Sitemap Generator' },
            { id: 'keyword-density-checker', name: 'Keyword Density Checker' },
            { id: 'word-counter', name: 'Word Counter' },
            { id: 'character-counter', name: 'Character Counter' },
            { id: 'url-slug-generator', name: 'URL Slug Generator' },
        ]
    },
    {
        id: 'social',
        name: 'Social Media',
        icon: MessageSquare,
        color: 'from-rose-500 to-rose-600',
        description: 'Social media utilities',
        tools: [
            { id: 'youtube-title-checker', name: 'YouTube Title Length Checker' },
            { id: 'youtube-tag-formatter', name: 'YouTube Tag Formatter' },
            { id: 'hashtag-generator', name: 'Hashtag Generator' },
            { id: 'instagram-caption-formatter', name: 'Instagram Caption Formatter' },
            { id: 'tweet-character-counter', name: 'Tweet Character Counter' },
        ]
    },
    {
        id: 'file',
        name: 'File Tools',
        icon: FolderOpen,
        color: 'from-violet-500 to-violet-600',
        description: 'File utilities & info',
        tools: [
            { id: 'file-size-converter', name: 'File Size Converter' },
            { id: 'zip-size-estimator', name: 'ZIP Size Estimator' },
            { id: 'file-extension-checker', name: 'File Extension Checker' },
            { id: 'mime-type-checker', name: 'MIME Type Checker' },
        ]
    },
    {
        id: 'unit',
        name: 'Unit Converters',
        icon: ArrowLeftRight,
        color: 'from-sky-500 to-sky-600',
        description: 'Unit conversion tools',
        tools: [
            { id: 'length-converter', name: 'Length Converter' },
            { id: 'weight-converter', name: 'Weight Converter' },
            { id: 'area-converter', name: 'Area Converter' },
            { id: 'volume-converter', name: 'Volume Converter' },
            { id: 'temperature-converter', name: 'Temperature Converter' },
            { id: 'speed-converter', name: 'Speed Converter' },
            { id: 'time-converter', name: 'Time Converter' },
            { id: 'currency-converter', name: 'Currency Converter' },
            { id: 'storage-converter', name: 'Storage Converter' },
            { id: 'energy-converter', name: 'Energy Converter' },
            { id: 'pressure-converter', name: 'Pressure Converter' },
        ]
    },
    {
        id: 'fun',
        name: 'Fun Tools',
        icon: Gamepad2,
        color: 'from-fuchsia-500 to-fuchsia-600',
        description: 'Fun & entertainment',
        tools: [
            { id: 'random-name-picker', name: 'Random Name Picker' },
            { id: 'random-team-generator', name: 'Random Team Generator' },
            { id: 'random-quote-generator', name: 'Random Quote Generator' },
            { id: 'lucky-number-generator', name: 'Lucky Number Generator' },
            { id: 'spin-wheel', name: 'Spin Wheel' },
            { id: 'decision-maker', name: 'Decision Maker' },
            { id: 'yes-no-generator', name: 'Yes/No Generator' },
        ]
    },
];

export function getToolById(toolId) {
    for (const cat of categories) {
        const tool = cat.tools.find(t => t.id === toolId);
        if (tool) return { ...tool, category: cat };
    }
    return null;
}

export function getCategoryById(catId) {
    return categories.find(c => c.id === catId) || null;
}